//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ident_Archiver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ident_Archiver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffmpeg was not found. Please install ffmpeg and add its location in the PATH environment variable..
        /// </summary>
        internal static string Error_FFMPEG_Not_Found_Content {
            get {
                return ResourceManager.GetString("Error_FFMPEG_Not_Found_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffmpeg not found.
        /// </summary>
        internal static string Error_FFMPEG_Not_Found_Title {
            get {
                return ResourceManager.GetString("Error_FFMPEG_Not_Found_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out all required fields..
        /// </summary>
        internal static string Error_Required_Fields_Content {
            get {
                return ResourceManager.GetString("Error_Required_Fields_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required fields.
        /// </summary>
        internal static string Error_Required_Fields_Title {
            get {
                return ResourceManager.GetString("Error_Required_Fields_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt-dlp was not found. Please install yt-dlp and add its location in the settings..
        /// </summary>
        internal static string Error_Ytdlp_Not_Found_Content {
            get {
                return ResourceManager.GetString("Error_Ytdlp_Not_Found_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yt-dlp was not found.
        /// </summary>
        internal static string Error_Ytdlp_Not_Found_Title {
            get {
                return ResourceManager.GetString("Error_Ytdlp_Not_Found_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy....
        /// </summary>
        internal static string Status_Busy {
            get {
                return ResourceManager.GetString("Status_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
    }
}
